on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

name: Render and Publish

permissions:
    contents: write
    pages: write

jobs:
    codespell:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: codespell-project/actions-codespell@master

    build-deploy:
        runs-on: ubuntu-latest
        steps:

            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2
              with:
                # To install LaTeX to build PDF book
                tinytex: true

            - name: Render Quarto
              uses: quarto-dev/quarto-actions/render@v2


            - name: Publish to GitHub Pages
              if: github.event_name != 'pull_request'
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                render: false
                target: gh-pages
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit PDF
              if: github.event_name != 'pull_request'
              uses: EndBug/add-and-commit@v9
              with:
                add: '_manuscript/index.pdf'
                author_name: 'GitHub Actions'
                message: 'Add paper.pdf at ${{ github.sha }}'
                new_branch: products
                push: origin products --force

            - name: Commit DOCX
              if: github.event_name != 'pull_request'
              uses: EndBug/add-and-commit@v9
              with:
                add: '_manuscript/index.docx'
                author_name: 'GitHub Actions'
                message: 'Add paper.doxc at ${{ github.sha }}'
                new_branch: products
                push: origin products --force
